export const SET_TOKEN = "SET_TOKEN";
export const SET_MENU = "SET_MENU";

export const GET_MENU_BY_USER_REQUEST = "GET_MENU_BY_USER_REQUEST";
export const GET_MENU_BY_USER_SUCCESS = "GET_MENU_BY_USER_SUCCESS";
export const GET_MENU_BY_USER_FAILURE = "GET_MENU_BY_USER_FAILURE";
export const GET_TOKEN_REQUEST = "GET_TOKEN_REQUEST";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_FAILURE = "GET_TOKEN_FAILURE";
